// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type signalsnoopEvent struct {
	Pid        uint32
	Tid        uint32
	Timestamp  uint64
	Comm       [16]int8
	EventType  uint8
	_          [7]byte
	Retval     int64
	StackDepth int32
	_          [4]byte
	Stack      [50]uint64
	Regs       signalsnoopUserRegs
	RegsValid  uint8
	_          [7]byte
	StackProbe signalsnoopStackProbe
}

type signalsnoopStackProbe struct {
	Val0    uint64
	ValM128 uint64
	ValM568 uint64
	Err0    int32
	ErrM128 int32
	ErrM568 int32
	_       [4]byte
}

type signalsnoopUserRegs struct {
	Ip    uint64
	Sp    uint64
	Flags uint64
	Ax    uint64
	Bx    uint64
	Cx    uint64
	Dx    uint64
	Si    uint64
	Di    uint64
	Bp    uint64
	R8    uint64
	R9    uint64
	R10   uint64
	R11   uint64
	R12   uint64
	R13   uint64
	R14   uint64
	R15   uint64
}

// loadSignalsnoop returns the embedded CollectionSpec for signalsnoop.
func loadSignalsnoop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SignalsnoopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load signalsnoop: %w", err)
	}

	return spec, err
}

// loadSignalsnoopObjects loads signalsnoop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*signalsnoopObjects
//	*signalsnoopPrograms
//	*signalsnoopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSignalsnoopObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSignalsnoop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// signalsnoopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type signalsnoopSpecs struct {
	signalsnoopProgramSpecs
	signalsnoopMapSpecs
}

// signalsnoopSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type signalsnoopProgramSpecs struct {
	KprobeDoCoredump           *ebpf.ProgramSpec `ebpf:"kprobe_do_coredump"`
	KprobeDoGroupExit          *ebpf.ProgramSpec `ebpf:"kprobe_do_group_exit"`
	KprobeForceFatalSig        *ebpf.ProgramSpec `ebpf:"kprobe_force_fatal_sig"`
	KprobeForceSig             *ebpf.ProgramSpec `ebpf:"kprobe_force_sig"`
	KprobeForceSigsegv         *ebpf.ProgramSpec `ebpf:"kprobe_force_sigsegv"`
	KprobeGetSignal            *ebpf.ProgramSpec `ebpf:"kprobe_get_signal"`
	KprobeSignalSetupDone      *ebpf.ProgramSpec `ebpf:"kprobe_signal_setup_done"`
	KprobeVfsCoredump          *ebpf.ProgramSpec `ebpf:"kprobe_vfs_coredump"`
	KprobeX64SetupRtFrame      *ebpf.ProgramSpec `ebpf:"kprobe_x64_setup_rt_frame"`
	KretprobeGetSignal         *ebpf.ProgramSpec `ebpf:"kretprobe_get_signal"`
	KretprobeX64SetupRtFrame   *ebpf.ProgramSpec `ebpf:"kretprobe_x64_setup_rt_frame"`
	TracepointSchedProcessFree *ebpf.ProgramSpec `ebpf:"tracepoint__sched_process_free"`
}

// signalsnoopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type signalsnoopMapSpecs struct {
	Events                 *ebpf.MapSpec `ebpf:"events"`
	X64SetupRtFrameSignals *ebpf.MapSpec `ebpf:"x64_setup_rt_frame__signals"`
}

// signalsnoopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSignalsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type signalsnoopObjects struct {
	signalsnoopPrograms
	signalsnoopMaps
}

func (o *signalsnoopObjects) Close() error {
	return _SignalsnoopClose(
		&o.signalsnoopPrograms,
		&o.signalsnoopMaps,
	)
}

// signalsnoopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSignalsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type signalsnoopMaps struct {
	Events                 *ebpf.Map `ebpf:"events"`
	X64SetupRtFrameSignals *ebpf.Map `ebpf:"x64_setup_rt_frame__signals"`
}

func (m *signalsnoopMaps) Close() error {
	return _SignalsnoopClose(
		m.Events,
		m.X64SetupRtFrameSignals,
	)
}

// signalsnoopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSignalsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type signalsnoopPrograms struct {
	KprobeDoCoredump           *ebpf.Program `ebpf:"kprobe_do_coredump"`
	KprobeDoGroupExit          *ebpf.Program `ebpf:"kprobe_do_group_exit"`
	KprobeForceFatalSig        *ebpf.Program `ebpf:"kprobe_force_fatal_sig"`
	KprobeForceSig             *ebpf.Program `ebpf:"kprobe_force_sig"`
	KprobeForceSigsegv         *ebpf.Program `ebpf:"kprobe_force_sigsegv"`
	KprobeGetSignal            *ebpf.Program `ebpf:"kprobe_get_signal"`
	KprobeSignalSetupDone      *ebpf.Program `ebpf:"kprobe_signal_setup_done"`
	KprobeVfsCoredump          *ebpf.Program `ebpf:"kprobe_vfs_coredump"`
	KprobeX64SetupRtFrame      *ebpf.Program `ebpf:"kprobe_x64_setup_rt_frame"`
	KretprobeGetSignal         *ebpf.Program `ebpf:"kretprobe_get_signal"`
	KretprobeX64SetupRtFrame   *ebpf.Program `ebpf:"kretprobe_x64_setup_rt_frame"`
	TracepointSchedProcessFree *ebpf.Program `ebpf:"tracepoint__sched_process_free"`
}

func (p *signalsnoopPrograms) Close() error {
	return _SignalsnoopClose(
		p.KprobeDoCoredump,
		p.KprobeDoGroupExit,
		p.KprobeForceFatalSig,
		p.KprobeForceSig,
		p.KprobeForceSigsegv,
		p.KprobeGetSignal,
		p.KprobeSignalSetupDone,
		p.KprobeVfsCoredump,
		p.KprobeX64SetupRtFrame,
		p.KretprobeGetSignal,
		p.KretprobeX64SetupRtFrame,
		p.TracepointSchedProcessFree,
	)
}

func _SignalsnoopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed signalsnoop_bpfel_x86.o
var _SignalsnoopBytes []byte
